### ISSUE TITLE
Add other gamemodes (taiko, ctb, mania) to !recalc commands

### ISSUE THREAD

**Issue by SHA-256-hash** [osuAkatsuki/bancho.py#101]
that's useful to recalc pp in all maps to live test changes made in oppai-ng <3

**Comment by atteure** [comment]
Already exists inside of the !recalc command (code is here: https://github.com/cmyui/gulag/blob/master/constants/commands.py#L955)

**Comment by cmyui** [comment]
Still not sure how this will scale in python with my cursed oppai-ng setup to the size of ~akatsuki but it's worth a shot, will probably get around to this soon.

**Comment by cmyui** [comment]
Oh woops, this has been added as of [v3.5.0](https://github.com/cmyui/gulag/commit/88cdc3b4c3e1361b52f4757743d810af325b0512) for osu!standard.
