### ISSUE TITLE
Gulag helper script

### ISSUE THREAD

**Issue by ghost** [osuAkatsuki/bancho.py#119]
As per #111, I wrote a helper script for gulag: <https://github.com/ospensory/gulag/commit/61b1f58dbbad6520c9a620940be1238dc6d9aa0d>. Let me know about your thoughts. If it's merge-able then I need to rework on the script to handle the existing directory.

**Comment by cmyui** [comment]
Oh sweet, from first glances it looks pretty decently thought out & organized. Something like this is definitely mergeable, but my bash scripting skills aren't great and I want to do an actual review of it so you'll have to give me a bit to get around to it (been rather busy irl lately so gulag has been on the backburner overall).

But yea leave it up, even if it takes a while I'll get around to it eventually :) thanks for the effort!

**Comment by m0lese** [comment]
Sure, take your time :D

**Comment by yo-ru** [comment]
Closed for inactivity.
