### ISSUE TITLE
Ranking tab loading loop & registering from osu not working

### ISSUE THREAD

**Issue by Bajgerek** [osuAkatsuki/bancho.py#211]
All was working untill i restarted vps now ranking tab stuck on 
![image](https://user-images.githubusercontent.com/65111609/161383479-d95ed536-c072-48cb-9c0d-a5010a66e963.png)

Note: I'm Using gulag v4.1.5 beacuse bancho.py is not working on my vps

**Comment by Bajgerek** [comment]
now registering from osu stopped working

**Comment by tsunyoku** [comment]
we are not going to provide support for a version that old. chances are this is an issue with connectively, not gulag itself regardless.
