### ISSUE TITLE
Switch to go-migrate as a database migration & seeding system

### ISSUE THREAD

**Issue by cmyui** [osuAkatsuki/bancho.py#263]
At the moment, bancho.py uses my diy-esque one-way migration system i wrote before i even knew migration systems existed.

This issue aims to clean this up and switch to a more popular & reliable system - [go-migrate](https://github.com/golang-migrate/migrate).

**Comment by cmyui** [comment]
Really need to do this.. only going to get worse..

**Comment by tsunyoku** [comment]
closing this because of #632 going in the direction of alembic, we can re-open in future if this changes
