### ISSUE TITLE
Critical PP calculation bug in osu!mania

### ISSUE THREAD

**Issue by def750** [osuAkatsuki/bancho.py#270]
When user is trying to submit a score in osu!mania, with ScoreV2 + NoFail. PP calculation gets literal autism and does stuff like that:
![image](https://user-images.githubusercontent.com/23400721/180862342-b9a81e8f-f538-4040-874e-7ceccf59c718.png)
I'd like to say that max pp on for example Triumph and regret is around 680 (With DT). 
Currently I just disabled score submission for this mods combination in mania but I guess there's a better way to solve this :^)

**Comment by tsunyoku** [comment]
this issue is probably better targetted towards the pp system repo and not us because it's not our issue

**Comment by def750** [comment]
> this issue is probably better targetted towards the pp system repo and not us because it's not our issue

I found why and it's actually gulag's bug

Mania without V2 has score multiplier for NoFail, (0.5x). V2 has no score multiplier for V2.
Score with V2NF gets passed to pp calculation as higher than maximum. For example let's take 950k score, pp system sees that it's with NF so it expects 500k score at most, 950k is obviously higher than maximum, it's like giving 10m score on some harumachi clover where max score is for example 300k, system will go crazy.

Good solution would be just applying score multipliers even in ScoreV2

**Comment by Pure-Peace** [comment]
Before switching the code of bancho.py to rosu-pp-py, you can fix this by `pip install peace-performance-python=2.0`, which uses the latest code from rosu-pp. 

I'm not sure if this problem exists with rosu-pp, you can try it

**Comment by tsunyoku** [comment]
we already use rosu-pp!

**Comment by Pure-Peace** [comment]
> we already use rosu-pp!

Currently this repository still uses peace-performance-python=1.1.2 `[requirements.txt](https://github.com/osuAkatsuki/bancho.py/blob/master/requirements.txt)` and some users reported the same issue to me.

So a temporary solution is necessary

**Comment by tsunyoku** [comment]
hm i thought we switched to rosu-pp :o
in that case i’ll likely just switch over to rosu-pp

**Comment by Pure-Peace** [comment]
> hm i thought we switched to rosu-pp :o in that case i’ll likely just switch over to rosu-pp

Yes, sorry, I haven't followed any of these in a while, and switching to rosu-pp is a better option.
