### ISSUE TITLE
Trademark advice

### ISSUE THREAD

**Issue by peppy** [osuAkatsuki/bancho.py#272]
I saw this project appear in github recommendations recently, along with related servers / websites / projects popping up around the place.

I am required to enforce my trademark and ask that the "osu!" is removed from the project and website names (directly – can of course be mentioned in relation to the osu! project / game), and not used in a way that looks official (aka "osu!something"). Could you please advise the best place to contact/discuss this if not here? I could not immediately find an email for contact.

Thanks.

**Comment by cmyui** [comment]
Hey!

Thanks for reaching out and I apologize - I can remove the usage of the "osu!" prefix in any official branding from both this repository as well as the [Akatsuki](https://akatsuki.pw) project as a whole immediately. Is this the only issue you see?

If you'd ever like to chat, my email is cmyuiosu@gmail.com or (if you prefer) I can be reached on Discord at cmyui#0425.

*P.S. I'm a very large fan of your work!!! It's been a significant seed in my programming career!*

**Comment by cmyui** [comment]
I've updated our website, discord, youtube, twitter, github, and have instructed other members of our team to notify of & replace any occurrences of "osu!Akatsuki" they come across.

**Comment by peppy** [comment]
That was the only concern. "bancho" is just an affectionate name so I have no issue nor control over that.

Thanks for the quick response.

**Comment by xSkyyy** [comment]
wtf peppy real
