### ISSUE TITLE
bug: several "anticheat" checks on score submission fail the submission and do not submit scores

### ISSUE THREAD

**Issue by def750** [osuAkatsuki/bancho.py#301]
After having some fun with score submission I can say that it's quite irritating that scores don't submit in some cases where error is raised, and I don't talk about errors where it is literally impossible. You might ask why? In some cases those scores can be legit, and some players actually put effort in playing, maybe it's their skill boost day, or maybe they have just hp passed some really hard map when they were rusty and some are cheating, every score matters. In case server admins want proof for that user score is submitted, and user is restricted anyways by anticheat/staff or anything in the world that can do it ;)

Here are few examples where scores should still be submitted:
**1. PP Caps**
When we were introducing pp caps with proper algorithm for that on our development server, we had first issue with that, pp caps just go and return the score sub. Pausing the whole score submission
**2. Same hash in db**
This is self explainatory i guess, it's just a proof needed for staff
**3. DB PP Caps**
Also self explainatory, database limit for pp is 10k, we want proof of a user
**4. Anticheat (in some cases)**
This affects both of mentioned earlier, in some cases user might be legit, it's their score after all, but in some cases he might be not, it's always useful stuff for admins to quickly react for false positives or have proof for people who can't click circles legitimately.

I have few ideas for the rework and maybe I'll do it myself if I find free time, but if someone wants to be faster than me I think the best way of doing that would be splitting score submission if 2 parts
1. Validation
2.  Submission
First we would validate the score, do anticheat measures, look for wierd stuff. If something would be wrong with the replay, skip to submission point with flag and alert the admins. Return with error if submission is impossible and inform the user about that as well as staff if it's bug.

**Comment by tsunyoku** [comment]
> 2. Same hash in db
This is self explainatory i guess, it's just a proof needed for staff

no. duplicate scores do not belong in the database. if you really  care about "proof", log these cases.

> 3. DB PP Caps
Also self explainatory, database limit for pp is 10k, we want proof of a user

this will be caught by the regular pp cap, anyway.

as for 1 and 4, i agree

**Comment by cmyui** [comment]
Yeah agree with @tsunyoku on #1 - if a client sends you a retry attempt and you already have stored the score, you should return them a success and consider the interaction complete.

PP cap is currently removed from the codebase but I would consider it the same under "anticheat" and scores should 100% be stored (imo it's actually much more important to store these scores over a typical score, since it's the evidence).

**Comment by cmyui** [comment]
Oo actually, it looks like how the codebase is currently handling it is quite sane in this regard:
https://github.com/osuAkatsuki/bancho.py/blob/a043f12e4a77f83faa180938214e02f79333872d/app/api/domains/osu.py#L719-L770

Though, the comment `# return b"error: ban"` sets a bad precedent - that would have this problem. Should probably fix that.

**Comment by cmyui** [comment]
Also noticed, pp cap (though commented out) will let `score.player` past:
https://github.com/osuAkatsuki/bancho.py/blob/a043f12e4a77f83faa180938214e02f79333872d/app/api/domains/osu.py#L822-L834

but will continue to use the player nonetheless later in the function; this seems quite unsafe - perhaps the logout should be executed only once score submission has fully completed?
https://github.com/osuAkatsuki/bancho.py/blob/a043f12e4a77f83faa180938214e02f79333872d/app/api/domains/osu.py#L856-L860

**Comment by cmyui** [comment]
Going to close this since it seems like the only issues I really found are related to code which is commented-out - feel free to reopen if you believe there are cases which should be reconsidered.
