### ISSUE TITLE
Redis credentials not handled correctly in the case of no user/password

### ISSUE THREAD

**Issue by IlyaKangin** [osuAkatsuki/bancho.py#303]
![изображение](https://user-images.githubusercontent.com/60034226/199675428-beb73bc8-f08c-462b-abe8-b4426d87d581.png)

i can't connect to bancho in osu and i get this error in server console

**Comment by 7ez** [comment]
change https://github.com/osuAkatsuki/bancho.py/blob/25135d859cd7ae75549a90834f1258fe05814dc6/app/settings.py#L33 to `REDIS_DSN = "redis://localhost"`

**Comment by cmyui** [comment]
i should just fix this properly already
