### ISSUE TITLE
a1024 /web/lastfm.php flag is unhandled

### ISSUE THREAD

**Issue by 23736** [osuAkatsuki/bancho.py#306]
I noticed that using Maple crack makes the client send `a1024` on lastFM and bancho.py does nothing about it lol

**Comment by 7ez** [comment]
Then make it do something and make a pr :trollface:

**Comment by minisbett** [comment]
Why does maple do that and what even is the lastfm parameter for

**Comment by 7ez** [comment]
> Why does maple do that and what even is the lastfm parameter for

https://github.com/osuAkatsuki/bancho.py/blob/master/app/api/domains/osu.py#L374-L375

**Comment by minisbett** [comment]
lol what

**Comment by tsunyoku** [comment]
there is some other things which send 1024 and i can’t seem to find a common trend with it yet; it’s not only the maple crack!

**Comment by minisbett** [comment]
can be closed no?

**Comment by tsunyoku** [comment]
not doing this for complicated reasons. if you care about it do it yourself
