### ISSUE TITLE
always return 404 error

### ISSUE THREAD

**Issue by shoei1944** [osuAkatsuki/bancho.py#330]
A little about connection:
Host -> SSH tunnel -> VPS -> Domain.

In general, I always get 404 when accessing bancho.py. In osu! the server is displayed as unavailable.

![image](https://user-images.githubusercontent.com/119505551/211152483-e84bc4db-bc4a-4b57-8837-9b9c23b7030d.png)

**Comment by cmyui** [comment]
iirc, this is ucased by the domain in .env not matching the domain in nginx

it should be `DOMAIN=sho20.ru` by the looks of it

**Comment by shoei1944** [comment]
forgot to replace
