### ISSUE TITLE
misc: make install doesn't work

### ISSUE THREAD

**Issue by Tian-MC** [osuAkatsuki/bancho.py#391]
Hi! when i try to do `make install`
it gives me this error:
`PIPENV_VENV_IN_PROJECT=1 pipenv install
/bin/sh: 1: pipenv: not found
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 127`

What i have to do?

**Comment by minisbett** [comment]
iirc this can be caused if setup tools was not installed properly, are you sure you didn't skip the instruction before `make install`?

**Comment by NiceAesth** [comment]
This is not an issue with `bancho.py`. You have not installed pipenv. Follow the instructions again.
