### ISSUE TITLE
misc: create indexes for common fields to improve query performance

### ISSUE THREAD

**Issue by TrueRou** [osuAkatsuki/bancho.py#395]
Its a problem that bancho.py doesn't originally create indexes for common fields like map_md5 and userid in scores table, filename in maps table, for example.
It's significant for a medium or large server to query with a indexed table.

**Comment by cmyui** [comment]
Yeah, I've been wanting to do this for a while - pretty high priority I'd say.

Tricky to find enough data to accurately test it with - ideally I'd like to do it with Akatsuki's full database, but we don't have an updated migration script..

**Comment by cmyui** [comment]
@xxcherry by any chance, happen to have that old akatsuki->bancho.py migration script lying around anywhere?

**Comment by tsunyoku** [comment]
> @xxCherry by any chance, happen to have that old akatsuki->bancho.py migration script lying around anywhere?

hey we wrote one remember :P
no clue where it is, but we made one

**Comment by tsunyoku** [comment]
resolved in #625
