### ISSUE TITLE
bug: When I run "make install", I got an error "Failed to build a native library through cargo"

### ISSUE THREAD

**Issue by mames1dev** [osuAkatsuki/bancho.py#401]
### Describe the bug

I get the error in the title, I have no knowledge of "rust" and cannot deal with it myself. I would like to know how to deal with it.

### To Reproduce

run "make install"
occur these error.

### Expected behavior

i dont have knowledge of "rust". so I don't know why this error occurs

### bancho.py Version

maybe 3.2.2

### Python Version

3.9.X (Default)

### Relevant log output

```shell
An error occurred while installing git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting akatsuki-pp-py
[pipenv.exceptions.InstallError]:   Cloning https://github.com/osuAkatsuki/akatsuki-pp-py (to revision abd33445a4f48ddf69c8e7996f7e9ed7340606a0) to /tmp/pip-install-exvh28ug/akatsuki-pp-py_4ace14de6d3a4a429343a70aa7b90462
[pipenv.exceptions.InstallError]:   Resolved https://github.com/osuAkatsuki/akatsuki-pp-py to commit abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): started
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): finished with status 'done'
[pipenv.exceptions.InstallError]: Building wheels for collected packages: akatsuki-pp-py
[pipenv.exceptions.InstallError]:   Building wheel for akatsuki-pp-py (pyproject.toml): started
[pipenv.exceptions.InstallError]:   Building wheel for akatsuki-pp-py (pyproject.toml): finished with status 'error'
[pipenv.exceptions.InstallError]: Failed to build akatsuki-pp-py
[pipenv.exceptions.InstallError]: Running command git clone --filter=blob:none --quiet https://github.com/osuAkatsuki/akatsuki-pp-py /tmp/pip-install-exvh28ug/akatsuki-pp-py_4ace14de6d3a4a429343a70aa7b90462
[pipenv.exceptions.InstallError]:   Running command git rev-parse -q --verify 'sha^abd33445a4f48ddf69c8e7996f7e9ed7340606a0'
[pipenv.exceptions.InstallError]:   Running command git fetch -q https://github.com/osuAkatsuki/akatsuki-pp-py abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   Running command git checkout -q abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Building wheel for akatsuki-pp-py (pyproject.toml) did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [71 lines of output]
[pipenv.exceptions.InstallError]:       Running `maturin pep517 build-wheel -i /home/mames1/osu/bancho.py/.venv/bin/python --compatibility off`
[pipenv.exceptions.InstallError]:          Compiling target-lexicon v0.12.5
[pipenv.exceptions.InstallError]:          Compiling autocfg v1.1.0
[pipenv.exceptions.InstallError]:          Compiling proc-macro2 v1.0.49
[pipenv.exceptions.InstallError]:          Compiling once_cell v1.16.0
[pipenv.exceptions.InstallError]:          Compiling libc v0.2.139
[pipenv.exceptions.InstallError]:          Compiling unicode-ident v1.0.6
[pipenv.exceptions.InstallError]:          Compiling quote v1.0.23
[pipenv.exceptions.InstallError]:          Compiling syn v1.0.107
[pipenv.exceptions.InstallError]:          Compiling parking_lot_core v0.9.5
[pipenv.exceptions.InstallError]:          Compiling cfg-if v1.0.0
[pipenv.exceptions.InstallError]:          Compiling scopeguard v1.1.0
[pipenv.exceptions.InstallError]:          Compiling smallvec v1.10.0
[pipenv.exceptions.InstallError]:          Compiling unindent v0.1.11
[pipenv.exceptions.InstallError]:          Compiling indoc v1.0.8
[pipenv.exceptions.InstallError]:          Compiling akatsuki-pp v0.9.3 (https://github.com/osuAkatsuki/akatsuki-pp-rs?rev=e22fe936337f3306fde2afec065f943c05e344f3#e22fe936)
[pipenv.exceptions.InstallError]:          Compiling lock_api v0.4.9
[pipenv.exceptions.InstallError]:          Compiling memoffset v0.6.5
[pipenv.exceptions.InstallError]:       error: could not compile `akatsuki-pp` due to 5 previous errors
[pipenv.exceptions.InstallError]:       warning: build failed, waiting for other jobs to finish...
[pipenv.exceptions.InstallError]:       💥 maturin failed
[pipenv.exceptions.InstallError]:         Caused by: Failed to build a native library through cargo
[pipenv.exceptions.InstallError]:         Caused by: Cargo build finished with "exit status: 101": `cargo rustc --manifest-path Cargo.toml --message-format json --release --lib --`
[pipenv.exceptions.InstallError]:       🔗 Found pyo3 bindings
[pipenv.exceptions.InstallError]:       🐍 Found CPython 3.9 at /home/mames1/osu/bancho.py/.venv/bin/python
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:         --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/taiko/difficulty_object.rs:42:36
[pipenv.exceptions.InstallError]:          |
[pipenv.exceptions.InstallError]:       42 |         let note_idx = base.is_hit.then_some(lists.notes.len());
[pipenv.exceptions.InstallError]:          |                                    ^^^^^^^^^
[pipenv.exceptions.InstallError]:          |
[pipenv.exceptions.InstallError]:          = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:          --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/reader.rs:141:22
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:       141 |                     .then_some(idx + 17)
[pipenv.exceptions.InstallError]:           |                      ^^^^^^^^^
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:           = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:          --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/reader.rs:238:67
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:       238 |             .find_map(|(i, byte)| (!matches!(byte, b' ' | b'\t')).then_some(i + 1))
[pipenv.exceptions.InstallError]:           |                                                                   ^^^^^^^^^
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:           = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:           --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/mod.rs:625:56
[pipenv.exceptions.InstallError]:            |
[pipenv.exceptions.InstallError]:       625  |                         Some(Some(len)) => (len > 0.0).then_some(len),
[pipenv.exceptions.InstallError]:            |                                                        ^^^^^^^^^
[pipenv.exceptions.InstallError]:       ...
[pipenv.exceptions.InstallError]:       1015 |         parse_hitobjects_body!(self, reader, section)
[pipenv.exceptions.InstallError]:            |         --------------------------------------------- in this macro invocation
[pipenv.exceptions.InstallError]:            |
[pipenv.exceptions.InstallError]:            = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:            = note: this error originates in the macro `parse_hitobjects_body` (in Nightly builds, run with -Z macro-backtrace for more info)
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error: aborting due to 4 previous errors
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       For more information about this error, try `rustc --explain E0658`.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/mames1/osu/bancho.py/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for akatsuki-pp-py
[pipenv.exceptions.InstallError]: ERROR: Could not build wheels for akatsuki-pp-py, which is required to install pyproject.toml-based projects
ERROR: Couldn't install package: [Requirement(_name='akatsuki-pp-py', vcs='git', req=VCSRequirement(setup_path=None, extras=(), _uri_scheme=None, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=None, _has_hashed_name=False, _parsed_line=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, editable=None, uri='https://github.com/osuAkatsuki/akatsuki-pp-py', path=None, vcs='git', ref='abd33445a4f48ddf69c8e7996f7e9ed7340606a0', _repo=None, _base_line=None, name='akatsuki-pp-py', link=<Link git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py>, req=Requirement.parse('akatsuki-pp-py@ https://github.com/osuAkatsuki/akatsuki-pp-py')), markers=None, _specifiers='', index=None, editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None), Requirement(_name='akatsuki-pp-py', vcs='git', req=VCSRequirement(setup_path=None, extras=(), _uri_scheme=None, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=None, _has_hashed_name=False, _parsed_line=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, editable=None, uri='https://github.com/osuAkatsuki/akatsuki-pp-py', path=None, vcs='git', ref='abd33445a4f48ddf69c8e7996f7e9ed7340606a0', _repo=None, _base_line=None, name='akatsuki-pp-py', link=<Link git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py>, req=Requirement.parse('akatsuki-pp-py@ https://github.com/osuAkatsuki/akatsuki-pp-py')), markers=None, _specifiers='', index=None, editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None)]
 Package installation failed...
make: *** [Makefile:11: install] Error 1
```

**Comment by 7ez** [comment]
run `rustup update`

**Comment by mames1dev** [comment]
I ran "rustup update", but it did not solve the problem
![image](https://user-images.githubusercontent.com/88868436/218259526-6af74344-cf99-493c-90d0-3329daf19533.png)
![image](https://user-images.githubusercontent.com/88868436/218259535-7b551b10-ffde-4c15-b7c9-04e3a69b8379.png)

**Comment by 7ez** [comment]
did you install rust via the curl script in the installation guide

**Comment by mames1dev** [comment]
yes, i did.

**Comment by mames1dev** [comment]
my rust's version

![image](https://user-images.githubusercontent.com/88868436/218260097-655eb634-067a-480c-aa44-753934d3e80a.png)

**Comment by 7ez** [comment]
> my rust's version
> 
> ![image](https://user-images.githubusercontent.com/88868436/218260097-655eb634-067a-480c-aa44-753934d3e80a.png)

it doesn't seem like you did as the latest cargo/rustc version is 1.67.1 and the latest rustup version is 1.25.2

**Comment by mames1dev** [comment]
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.67.1 (d5a82bbd2 2023-02-07)

I ran this command. As a result, I got something like the image. What do I do from here?
![image](https://user-images.githubusercontent.com/88868436/218260828-220628a0-8875-4989-895e-9687f083013f.png)

**Comment by mames1dev** [comment]
sorry, i didn't paste command

curl https://sh.rustup.rs -sSf | sh -s -- -y

**Comment by 7ez** [comment]
try installing requirements again

**Comment by mames1dev** [comment]
I reinstalled it, but it was still at v1.6.1. The error was not repaired.
![image](https://user-images.githubusercontent.com/88868436/218261500-c69c51a9-6f51-40b9-9cd7-77e9d186c581.png)

**Comment by mames1dev** [comment]
My Error

`An error occurred while installing git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting akatsuki-pp-py
[pipenv.exceptions.InstallError]:   Cloning https://github.com/osuAkatsuki/akatsuki-pp-py (to revision abd33445a4f48ddf69c8e7996f7e9ed7340606a0) to /tmp/pip-install-hlq1xcjv/akatsuki-pp-py_9c9dd92a01cc49b69bad3ab3270b64f9
[pipenv.exceptions.InstallError]:   Resolved https://github.com/osuAkatsuki/akatsuki-pp-py to commit abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): started
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): finished with status 'done'
[pipenv.exceptions.InstallError]: Building wheels for collected packages: akatsuki-pp-py
[pipenv.exceptions.InstallError]:   Building wheel for akatsuki-pp-py (pyproject.toml): started
[pipenv.exceptions.InstallError]:   Building wheel for akatsuki-pp-py (pyproject.toml): finished with status 'error'
[pipenv.exceptions.InstallError]: Failed to build akatsuki-pp-py
[pipenv.exceptions.InstallError]: Running command git clone --filter=blob:none --quiet https://github.com/osuAkatsuki/akatsuki-pp-py /tmp/pip-install-hlq1xcjv/akatsuki-pp-py_9c9dd92a01cc49b69bad3ab3270b64f9
[pipenv.exceptions.InstallError]:   Running command git rev-parse -q --verify 'sha^abd33445a4f48ddf69c8e7996f7e9ed7340606a0'
[pipenv.exceptions.InstallError]:   Running command git fetch -q https://github.com/osuAkatsuki/akatsuki-pp-py abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   Running command git checkout -q abd33445a4f48ddf69c8e7996f7e9ed7340606a0
[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Building wheel for akatsuki-pp-py (pyproject.toml) did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [71 lines of output]
[pipenv.exceptions.InstallError]:       Running `maturin pep517 build-wheel -i /home/mames1/osu-server/bancho.py/.venv/bin/python --compatibility off`
[pipenv.exceptions.InstallError]:          Compiling target-lexicon v0.12.5
[pipenv.exceptions.InstallError]:          Compiling autocfg v1.1.0
[pipenv.exceptions.InstallError]:          Compiling proc-macro2 v1.0.49
[pipenv.exceptions.InstallError]:          Compiling once_cell v1.16.0
[pipenv.exceptions.InstallError]:          Compiling quote v1.0.23
[pipenv.exceptions.InstallError]:          Compiling libc v0.2.139
[pipenv.exceptions.InstallError]:          Compiling unicode-ident v1.0.6
[pipenv.exceptions.InstallError]:          Compiling syn v1.0.107
[pipenv.exceptions.InstallError]:          Compiling parking_lot_core v0.9.5
[pipenv.exceptions.InstallError]:          Compiling smallvec v1.10.0
[pipenv.exceptions.InstallError]:          Compiling cfg-if v1.0.0
[pipenv.exceptions.InstallError]:          Compiling scopeguard v1.1.0
[pipenv.exceptions.InstallError]:          Compiling unindent v0.1.11
[pipenv.exceptions.InstallError]:          Compiling indoc v1.0.8
[pipenv.exceptions.InstallError]:          Compiling akatsuki-pp v0.9.3 (https://github.com/osuAkatsuki/akatsuki-pp-rs?rev=e22fe936337f3306fde2afec065f943c05e344f3#e22fe936)
[pipenv.exceptions.InstallError]:          Compiling lock_api v0.4.9
[pipenv.exceptions.InstallError]:          Compiling memoffset v0.6.5
[pipenv.exceptions.InstallError]:       error: could not compile `akatsuki-pp` due to 5 previous errors
[pipenv.exceptions.InstallError]:       warning: build failed, waiting for other jobs to finish...
[pipenv.exceptions.InstallError]:       💥 maturin failed
[pipenv.exceptions.InstallError]:         Caused by: Failed to build a native library through cargo
[pipenv.exceptions.InstallError]:         Caused by: Cargo build finished with "exit status: 101": `cargo rustc --manifest-path Cargo.toml --message-format json --release --lib --`
[pipenv.exceptions.InstallError]:       🔗 Found pyo3 bindings
[pipenv.exceptions.InstallError]:       🐍 Found CPython 3.9 at /home/mames1/osu-server/bancho.py/.venv/bin/python
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:         --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/taiko/difficulty_object.rs:42:36
[pipenv.exceptions.InstallError]:          |
[pipenv.exceptions.InstallError]:       42 |         let note_idx = base.is_hit.then_some(lists.notes.len());
[pipenv.exceptions.InstallError]:          |                                    ^^^^^^^^^
[pipenv.exceptions.InstallError]:          |
[pipenv.exceptions.InstallError]:          = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:          --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/reader.rs:141:22
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:       141 |                     .then_some(idx + 17)
[pipenv.exceptions.InstallError]:           |                      ^^^^^^^^^
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:           = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:          --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/reader.rs:238:67
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:       238 |             .find_map(|(i, byte)| (!matches!(byte, b' ' | b'\t')).then_some(i + 1))
[pipenv.exceptions.InstallError]:           |                                                                   ^^^^^^^^^
[pipenv.exceptions.InstallError]:           |
[pipenv.exceptions.InstallError]:           = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error[E0658]: use of unstable library feature 'bool_to_option'
[pipenv.exceptions.InstallError]:           --> /home/mames1/.cargo/git/checkouts/akatsuki-pp-rs-5f93c482ea376701/e22fe93/src/parse/mod.rs:625:56
[pipenv.exceptions.InstallError]:            |
[pipenv.exceptions.InstallError]:       625  |                         Some(Some(len)) => (len > 0.0).then_some(len),
[pipenv.exceptions.InstallError]:            |                                                        ^^^^^^^^^
[pipenv.exceptions.InstallError]:       ...
[pipenv.exceptions.InstallError]:       1015 |         parse_hitobjects_body!(self, reader, section)
[pipenv.exceptions.InstallError]:            |         --------------------------------------------- in this macro invocation
[pipenv.exceptions.InstallError]:            |
[pipenv.exceptions.InstallError]:            = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
[pipenv.exceptions.InstallError]:            = note: this error originates in the macro `parse_hitobjects_body` (in Nightly builds, run with -Z macro-backtrace for more info)
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       error: aborting due to 4 previous errors
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       For more information about this error, try `rustc --explain E0658`.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/mames1/osu-server/bancho.py/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for akatsuki-pp-py
[pipenv.exceptions.InstallError]: ERROR: Could not build wheels for akatsuki-pp-py, which is required to install pyproject.toml-based projects
ERROR: Couldn't install package: [Requirement(_name='akatsuki-pp-py', vcs='git', req=VCSRequirement(setup_path=None, extras=(), _uri_scheme=None, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=None, _has_hashed_name=False, _parsed_line=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, editable=None, uri='https://github.com/osuAkatsuki/akatsuki-pp-py', path=None, vcs='git', ref='abd33445a4f48ddf69c8e7996f7e9ed7340606a0', _repo=None, _base_line=None, name='akatsuki-pp-py', link=<Link git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py>, req=Requirement.parse('akatsuki-pp-py@ https://github.com/osuAkatsuki/akatsuki-pp-py')), markers=None, _specifiers='', index=None, editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None), Requirement(_name='akatsuki-pp-py', vcs='git', req=VCSRequirement(setup_path=None, extras=(), _uri_scheme=None, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=None, _has_hashed_name=False, _parsed_line=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, editable=None, uri='https://github.com/osuAkatsuki/akatsuki-pp-py', path=None, vcs='git', ref='abd33445a4f48ddf69c8e7996f7e9ed7340606a0', _repo=None, _base_line=None, name='akatsuki-pp-py', link=<Link git+https://github.com/osuAkatsuki/akatsuki-pp-py@abd33445a4f48ddf69c8e7996f7e9ed7340606a0#egg=akatsuki-pp-py>, req=Requirement.parse('akatsuki-pp-py@ https://github.com/osuAkatsuki/akatsuki-pp-py')), markers=None, _specifiers='', index=None, editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=akatsuki-pp-py, path=None, uri=git+https://github.com/osuAkatsuki/akatsuki-pp-py, extras=(), markers=None, vcs=git, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None)]
 Package installation failed...`

**Comment by mames1dev** [comment]
sorry, i solved this problem! thank you!

**Comment by cfgexe** [comment]
how did you fix this? im getting the same error

**Comment by 7ez** [comment]
> how did you fix this? im getting the same error

reread the conversation

**Comment by mames1dev** [comment]
In my case, I rebuild linux, and it fixed ti.
