### ISSUE TITLE
bug: bancho.py 4.7.2 was broken.

### ISSUE THREAD

**Issue by hzswdef** [osuAkatsuki/bancho.py#406]
### Describe the bug

Avatars not working.
All maps without ranked state (loved/ranked/etc.).
While creating a lobby on the multi you will always create a room with 16 opened slots.

When I reverted ~1 year of commits the server started working much better.

### To Reproduce

-

### Expected behavior

-

### bancho.py Version

4.7.2

### Python Version

3.9.X (Default)

**Comment by minisbett** [comment]
As for the "avatars" not working, can you show us your Cloudflare DNS settings and nginx file? As for the ranked loved stuff, did you provide an osu! api key in the .env file? As for the multi slots thing, that might be an actual bug

**Comment by hzswdef** [comment]
Hi @minisbett , here is the Cloudflare DNS and nginx -

![image](https://user-images.githubusercontent.com/89301466/219042950-5aff01fb-5db0-4b99-a092-7c5ca9286150.png)

```
# nginx.conf of the 4.6.4 version which is working for me
# I'm not sure if there are any changes between the latest and 4.6.4v.

upstream bancho {
        server unix:/tmp/bancho.sock fail_timeout=0;
}

# c[e4]?.ppy.sh is used for bancho
# osu.ppy.sh is used for /web, /api, etc.
# a.ppy.sh is used for osu! avatars

server {
        listen 443 ssl;

        server_name ~^(?:c[e4]?|osu|b|api)\.kurai\.pw$;

        ssl_certificate    /root/.cert/fullchain.pem;
        ssl_certificate_key /root/.cert/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header Host $http_host;
                add_header Access-Control-Allow-Origin *;
                proxy_redirect off;
                proxy_pass http://bancho;
        }
}

server {
        listen 443 ssl;

        server_name assets.kurai.pw;

        ssl_certificate    /root/.cert/fullchain.pem;
        ssl_certificate_key /root/.cert/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        location / {
                default_type image/png;
                root /var/kurai/kurai.pw/.data/assets/;
        }
}

server {
        listen 443 ssl;

        server_name a.kurai.pw;

        ssl_certificate    /root/.cert/fullchain.pem;
        ssl_certificate_key /root/.cert/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";

        location / {
                root /var/kurai/kurai.pw/.data/avatars;
                try_files $uri $uri.png $uri.jpg $uri.gif $uri.jpeg $uri.jfif /default.jpg = 404;
        }
}
```

osu! api key was placed in the `.env` file.
Note: I used api v1 from https://osu.ppy.sh/p/api

**Comment by hzswdef** [comment]
I didn't mention it but instead of avatars I get the default `osu.domain.com` (or any other sub-domains) response

![image](https://user-images.githubusercontent.com/89301466/219044398-fc7d05a5-6d07-4e26-8f01-bdd093e4b98f.png)

**Comment by minisbett** [comment]
Idk maybe try to not use full TLS encryption and just flexible instead, meaning you change that setting in CF and then remove all ssl stuff from your nginx config, followed by replacing the listen 443 ssl with listen 80, it likely is not the issue but chances are it fixes this issue on the way, happened in the past

**Comment by hzswdef** [comment]
@minisbett do you know any servers which currently use bancho.py 4.7.2?

**Comment by 0i8** [comment]
> @minisbett do you know any servers which currently use bancho.py 4.7.2?

i do! i can confirm that multi is broken (e.g. "assert slot is not None" in player.py returns AssertionError) but my avatar server works just fine

**Comment by NiceAesth** [comment]
avatars are unrelated to this issue and so are all misconfiguration things you have going on (use discussions for those please)

my main issue is that i have no clue what you are actually trying to report as you have provided very little information.

if you can provide more information about what fails (RELATED to bancho.py code) and when it fails (e.g. the reproduction steps you did not fill in) a fix will be looked into

**Comment by NiceAesth** [comment]
mind if you provide what you did to fix your issue so others may find it?
