### ISSUE TITLE
bug: osu crashes when changing songs during multiplayer

### ISSUE THREAD

**Issue by mames1dev** [osuAkatsuki/bancho.py#435]
### Describe the bug

osu crashes when changing songs.

### To Reproduce

1. Start multiplayer with multiple players
2. Change the map
3. Screen blacks out and osu crashes

### Expected behavior

osu crashes when changing songs.

### bancho.py Version

Version as of January 2023

### Python Version

3.9.X (Default)

### Relevant log output

```shell
[08:05:10AM] Validation error on http://osu.mamesosu.net/web/osu-error.php
[{'ctx': {'given': '4',
          'permitted': ('Osu', 'Taiko', 'CatchTheBeat', 'OsuMania')},
  'loc': ('body', 'gamemode'),
  'msg': "unexpected value; permitted: 'Osu', 'Taiko', 'CatchTheBeat', "
         "'OsuMania'",
  'type': 'value_error.const'}]
[08:05:10AM] [POST] 422 osu.mamesosu.net/web/osu-error.php | Request took: 5.44 msec
```

**Comment by JKBGL** [comment]
You probably have a broken map on your client.
bancho.py and other server implementations have nothing to do with client crashes. The output log you sent is not relevant to this issue since the server implementation does not yet support `osu-error.php`. And errors such as validation do not crash the server instance.

**Comment by 7ez** [comment]
> You probably have a broken map on your client.
> bancho.py and other server implementations have nothing to do with client crashes. The output log you sent is not relevant to this issue since the server implementation does not yet support `osu-error.php`. And errors such as validation do not crash the server instance.

i fixed the cause already though

**Comment by mames1dev** [comment]
> > You probably have a broken map on your client.
> > bancho.py and other server implementations have nothing to do with client crashes. The output log you sent is not relevant to this issue since the server implementation does not yet support `osu-error.php`. And errors such as validation do not crash the server instance.
> 
> i fixed the cause already though

What should I do? If you have a source program that I need to replace, please let me know.

**Comment by 7ez** [comment]
> > > You probably have a broken map on your client.
> > > bancho.py and other server implementations have nothing to do with client crashes. The output log you sent is not relevant to this issue since the server implementation does not yet support `osu-error.php`. And errors such as validation do not crash the server instance.
> > 
> > 
> > i fixed the cause already though
> 
> What should I do for a solution? If i have a source program that I need to replace, please let me know.

Update

**Comment by mames1dev** [comment]
How do I update bancho.py? Is it reinstallation, etc.?

**Comment by 0i8** [comment]
> How do I update bancho.py? Is it reinstallation, etc.?

`git pull`

**Comment by mames1dev** [comment]
> > How do I update bancho.py? Is it reinstallation, etc.?
> 
> `git pull`

thank you very much!
