### ISSUE TITLE
bug: v1 api endpoint /get_replay appears to be incomplete

### ISSUE THREAD

**Issue by kingdom5500** [osuAkatsuki/bancho.py#458]
### Describe the bug

replays downloaded from `v1/get_replay` cannot be processed by the client, because the replay headers are missing regardless of the `include_headers` parameter. presumably, `include_headers=True` should return a functioning `.osr` file, but the server code [seems to process it the other way around](https://github.com/osuAkatsuki/bancho.py/blob/65fabad0849c6eda3252f81ea11aa1c472cc7e28/app/api/v1/api.py#L740).

even with this in mind, specifying `include_headers=False` still provides the same incomplete replay file because the `replay_data` variable which contains the headers is never actually affixed to the raw replay file before it is sent off.

### To Reproduce

1. download the .osr file from https://api.skrungly.com/v1/get_replay?id=1447&include_headers=True (also ensure you have [the map](https://osu.ppy.sh/beatmapsets/677687#osu/1490588))
2. import into your game
3. stonks!

![image](https://github.com/osuAkatsuki/bancho.py/assets/37349466/422a81dc-de32-40e9-80ca-bd46b1d267d0)

### Expected behavior

when specifying `include_headers=True`, the `.osr` file should include headers. 

### bancho.py Version

latest

### Python Version

3.9.X (Default)

### Additional context

i understand that the v1 api is soon to be deprecated, but to my knowledge it is currently the only way to receive certain data (such as whole replay files) from the server, and so it should at least be functional in the meantime.

**Comment by g1-1-1** [comment]
can you check to see if #458 fixes this for you? i run the changes in that PR on my main production server ([example replay from the server](https://api.halcyon.moe/get_replay?id=65415) [and the map you'll need](https://osu.ppy.sh/beatmapsets/490121#osu/1044728))

**Comment by kingdom5500** [comment]
yep! i looked but somehow didn't spot your PR in the works. literally just implemented a nearly-identical fix for my own server hehe.

banger of a map btw! :D

**Comment by g1-1-1** [comment]
i had just made it ~5 minutes after you made this issue, so i can see how you missed it lol
glad it worked +1
