### ISSUE TITLE
misc: How to use bancho.py with Nginx Proxy Manager

### ISSUE THREAD

**Issue by Listum** [osuAkatsuki/bancho.py#482]
I want to use bancho.py  with "Nginx Proxy Manager" can I somehow connect directly to the ip? Also, if I need configurations in "Nginx Proxy Manager" itself, which ones should I specify?

**Comment by 7ez** [comment]
"directly to the ip"?

**Comment by g1-1-1** [comment]
i think they want to use their ip as the domain to use with nginx instead of an actual domain

**Comment by minisbett** [comment]
That would not work since the client wouldn't support that, you need subdomains and those don't exist on an IP layer

**Comment by Listum** [comment]
That's the thing, it does. The problem is the complexity of your ngnix. There is a forced connection to the subdomain and forced use of TLS. In my case, connection to the subdomain and TLS connection is done by Proxy Manager. Proxy Manager requires an IP:Port on the local network to connect to the service, which I can't connect to due to domain enforcement

**Comment by minisbett** [comment]
The subdomains are necessary in order for the osu client to work, it's not like bpy chooses to have those specific subdomains

**Comment by Listum** [comment]
Ok thx
