### ISSUE TITLE
misc: certificate path unfindable for manual install

### ISSUE THREAD

**Issue by Furdox** [osuAkatsuki/bancho.py#483]
I'm currently going through the manual install process but I'm stuck at [#configuring-a-reverse-proxy-well-use-nginx](https://github.com/osuAkatsuki/bancho.py/wiki/Setting-up-(Manual)#configuring-a-reverse-proxy-well-use-nginx).

It says `nginx: [emerg] cannot load certificate "/home/cmyui/certs/fullchain.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/home/cmyui/certs/fullchain.crt, r) error:10000080:BIO routines::no such file)` when trying to reload nginx (sudo nginx -s reload), which is obvious because it's not even my own home directory. I tried modifying the username just incase thinking it still wouldn't fix it and indeed it did not fix it.

There's mentions of the path being hardcoded in the docker-compose file but this isn't the Docker installation process so I am not using Docker. What should I do?

**Comment by minisbett** [comment]
Well you need to change the path to an SSL certificate. You basically have 3 options

1) Use flexible TLS option on Cloudflare, there should be instructions for it in the wiki I think
2) Use the origin certificate Cloudflare gives you for the ssl cert there
3) Generate your own certificate using some tool like openssl

**Comment by Furdox** [comment]
I don't use Cloudflare for website legacy reasons (yes ik it's dumb but whatever)
I'd be left with the last option. I remember an old version of bancho.py used openssl to generate a certificate, could I perhaps get the instuctions?

**Comment by Furdox** [comment]
> I don't use Cloudflare for website legacy reasons (yes ik it's dumb but whatever) I'd be left with the last option. I remember an old version of bancho.py used openssl to generate a certificate, could I perhaps get the instructions?

Nevermind I figured it out, it was stupidly simple.

**Comment by Furdox** [comment]
I also found the instructions I was talking about in post-setup.

**Comment by g1-1-1** [comment]
i think the problem was that you were using the default directory which you are supposed to change `/home/cmyui`

**Comment by Furdox** [comment]
> i think the problem was that you were using the default directory which you are supposed to change (`/home/cmyui`) -- you mentioned you changed this but the error log you posted does not indicate that

It does not say you need to change it, infact, it says that it doesn't matter.
