### ISSUE TITLE
bug: docker-compose.yml: services.nginx.ports array items[0,1] must be unique

### ISSUE THREAD

**Issue by magonyfur** [osuAkatsuki/bancho.py#492]
### Describe the bug

is docker im trying to use the nginx without ssl
i need help getting it to work
preferebly reacheble from localhost or 127.0.0.1

### To Reproduce

change 

SERVER_PORT=80

HOST_PORT=80

### Expected behavior

working and docker composing

### bancho.py Version

newest

### Python Version

3.9.X (Default)

**Comment by magonyfur** [comment]
close this bug i fixed it already, only cannot conect over localhost

**Comment by 7ez** [comment]
you can close it yourself
