### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by cmyui** [osuAkatsuki/bancho.py#95]
Codebase is getting really quite large now and errors *do* arise and are left unnoticed for longer than ideal, it's time for gulag to get some tests.

**Comment by cmyui** [comment]
tests for packet serialization added in https://github.com/osuAkatsuki/gulag/commit/3dc0f3ef939a68b8f99e38d8e7df2a505390baa7

**Comment by cmyui** [comment]
this is being kickstarted in #201

**Comment by tsunyoku** [comment]
score sub integration test is already covering 50% of the codebase alone, many more tests can be added but i don't think an issue as generic as this needs to remain open anymore
